#define _GNU_SOURCE
#include "faisal_sandbox_service.h"
#include <fcntl.h>
#include <string.h>
#include <unistd.h>
#include <stdio.h>
struct fsb_hdr { uint32_t magic; uint16_t version,kind; uint32_t size; uint64_t sequence; };
enum { FSB_REC_SANDBOX=1 };
static struct fsb_sandbox *find(struct fsb_service*s,uint64_t id){size_t i;for(i=0;i<s->count;i++)if(s->sandboxes[i].sandbox_id==id)return&s->sandboxes[i];return 0;}
static int write_record(struct fsb_service*s,const struct fsb_sandbox*b){struct fsb_hdr h={FSB_MAGIC,FSB_VERSION,FSB_REC_SANDBOX,sizeof *b,s->next_sequence++};if(write(s->fd,&h,sizeof h)!=(ssize_t)sizeof h||write(s->fd,b,sizeof*b)!=(ssize_t)sizeof*b||fsync(s->fd)<0)return FSB_ERR_IO;return FSB_OK;}
static int class_policy(uint32_t c,const struct fsb_policy*p){if(!p||!p->capability_mask)return FSB_ERR_POLICY;switch(c){case FSB_MEMORY:if(p->capability_mask&(FSB_CAP_COMMAND|FSB_CAP_DEPLOY|FSB_CAP_SECRET|FSB_CAP_DEVICE))return FSB_ERR_POLICY;break;case FSB_BROWSER:if(p->capability_mask&FSB_CAP_DEVICE)return FSB_ERR_POLICY;break;case FSB_BUG_FINDER:if(p->capability_mask&(FSB_CAP_DEPLOY|FSB_CAP_SECRET))return FSB_ERR_POLICY;break;case FSB_DEBUGGER:if(p->capability_mask&FSB_CAP_DEPLOY)return FSB_ERR_POLICY;break;case FSB_MODEL:if(p->capability_mask&(FSB_CAP_COMMAND|FSB_CAP_DEPLOY|FSB_CAP_SECRET))return FSB_ERR_POLICY;break;case FSB_SECRETS:if(!(p->capability_mask&FSB_CAP_SECRET)||p->network_mask)return FSB_ERR_POLICY;break;case FSB_DEPLOY_CANARY:if(!(p->capability_mask&FSB_CAP_DEPLOY)||!p->require_verification)return FSB_ERR_POLICY;break;case FSB_RECOVERY:if(!(p->capability_mask&FSB_CAP_RECOVERY)||!p->require_verification)return FSB_ERR_POLICY;break;default:break;}return FSB_OK;}
int fsb_replay(struct fsb_service*s){struct fsb_hdr h;struct fsb_sandbox b;if(!s||lseek(s->fd,0,SEEK_SET)<0)return FSB_ERR_ARGUMENT;s->count=0;s->next_sequence=1;for(;;){ssize_t n=read(s->fd,&h,sizeof h);if(!n)break;if(n!=(ssize_t)sizeof h||h.magic!=FSB_MAGIC||h.version!=FSB_VERSION||h.size!=sizeof b||read(s->fd,&b,sizeof b)!=(ssize_t)sizeof b)return FSB_ERR_CORRUPT;if(h.kind!=FSB_REC_SANDBOX||s->count>=FSB_MAX_SANDBOXES)return FSB_ERR_CORRUPT;struct fsb_sandbox*old=find(s,b.sandbox_id);if(old)*old=b;else s->sandboxes[s->count++]=b;s->next_sequence=h.sequence+1;if(b.sandbox_id>=s->next_id)s->next_id=b.sandbox_id+1;}return lseek(s->fd,0,SEEK_END)<0?FSB_ERR_IO:FSB_OK;}
int fsb_open(struct fsb_service*s,const char*p){if(!s||!p||strlen(p)>=sizeof s->path)return FSB_ERR_ARGUMENT;memset(s,0,sizeof*s);s->fd=open(p,O_RDWR|O_CREAT|O_APPEND,0600);if(s->fd<0)return FSB_ERR_IO;strncpy(s->path,p,sizeof(s->path)-1);pthread_mutex_init(&s->lock,0);s->lock_initialized=1;s->next_id=s->next_checkpoint=s->next_sequence=1;int r=fsb_replay(s);if(r)fsb_close(s);return r;}
void fsb_close(struct fsb_service*s){if(!s)return;if(s->lock_initialized)pthread_mutex_destroy(&s->lock);s->lock_initialized=0;if(s->fd>=0)close(s->fd);s->fd=-1;}
int fsb_create(struct fsb_service*s,uint32_t c,uint64_t agent,uint64_t parent,uint32_t tenant,const char*n,const struct fsb_policy*p,struct fsb_sandbox*out){struct fsb_sandbox*b;int r;if(!s||!n||!p||!out||!n[0]||strlen(n)>=FSB_MAX_NAME)return FSB_ERR_ARGUMENT;r=class_policy(c,p);if(r)return r;pthread_mutex_lock(&s->lock);if(s->count>=FSB_MAX_SANDBOXES){pthread_mutex_unlock(&s->lock);return FSB_ERR_FULL;}b=&s->sandboxes[s->count++];memset(b,0,sizeof*b);b->sandbox_id=s->next_id++;b->parent_id=parent;b->agent_id=agent;b->tenant_id=tenant;b->class_id=c;b->generation=1;b->state=FSB_CREATED;b->policy=*p;strncpy(b->name,n,sizeof b->name-1);r=write_record(s,b);if(r==FSB_OK)*out=*b;pthread_mutex_unlock(&s->lock);return r;}
int fsb_admit(const struct fsb_sandbox*b,uint64_t caps,uint64_t net,uint64_t fs,uint32_t require_ver){if(!b)return FSB_ERR_ARGUMENT;if(b->state!=FSB_CREATED&&b->state!=FSB_RECOVERED)return FSB_ERR_STATE;if(caps&~b->policy.capability_mask)return FSB_ERR_POLICY;if(net&~b->policy.network_mask)return FSB_ERR_POLICY;if(fs&~b->policy.filesystem_mask)return FSB_ERR_POLICY;if(require_ver&&!b->policy.require_verification)return FSB_ERR_AUTHORITY;return FSB_OK;}
static int transition(struct fsb_service*s,uint64_t id,uint32_t state,const char*reason,struct fsb_sandbox*out){struct fsb_sandbox*b;int r;if(!s||!out)return FSB_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);b=find(s,id);if(!b){pthread_mutex_unlock(&s->lock);return FSB_ERR_NOT_FOUND;}if(state==FSB_RUNNING&&b->state!=FSB_CREATED&&b->state!=FSB_RECOVERED){pthread_mutex_unlock(&s->lock);return FSB_ERR_STATE;}if(state==FSB_CHECKPOINTED&&b->state!=FSB_RUNNING){pthread_mutex_unlock(&s->lock);return FSB_ERR_STATE;}if((state==FSB_CANCELLED||state==FSB_FAILED)&&b->state!=FSB_RUNNING&&b->state!=FSB_CHECKPOINTED){pthread_mutex_unlock(&s->lock);return FSB_ERR_STATE;}b->state=state;b->generation++;if(reason)strncpy(b->failure_reason,reason,sizeof b->failure_reason-1);r=write_record(s,b);if(r==FSB_OK)*out=*b;pthread_mutex_unlock(&s->lock);return r;}
int fsb_start(struct fsb_service*s,uint64_t id,struct fsb_sandbox*out){return transition(s,id,FSB_RUNNING,0,out);}
int fsb_checkpoint(struct fsb_service*s,uint64_t id,uint64_t prov,uint64_t now,struct fsb_sandbox*out){int r;if(!s||!out)return FSB_ERR_ARGUMENT;r=transition(s,id,FSB_CHECKPOINTED,0,out);if(!r){pthread_mutex_lock(&s->lock);struct fsb_sandbox*b=find(s,id);b->checkpoint_id=s->next_checkpoint++;b->provenance_sequence=prov;b->generation++;(void)now;r=write_record(s,b);*out=*b;pthread_mutex_unlock(&s->lock);}return r;}
int fsb_cancel(struct fsb_service*s,uint64_t id,const char*reason,struct fsb_sandbox*out){return transition(s,id,FSB_CANCELLED,reason,out);}
int fsb_fail(struct fsb_service*s,uint64_t id,const char*reason,struct fsb_sandbox*out){return transition(s,id,FSB_FAILED,reason,out);}
int fsb_recover(struct fsb_service*s,uint64_t id,uint64_t prov,struct fsb_sandbox*out){struct fsb_sandbox*b;int r;if(!s||!out)return FSB_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);b=find(s,id);if(!b){pthread_mutex_unlock(&s->lock);return FSB_ERR_NOT_FOUND;}if(b->state!=FSB_FAILED&&b->state!=FSB_CHECKPOINTED){pthread_mutex_unlock(&s->lock);return FSB_ERR_STATE;}b->state=FSB_RECOVERED;b->generation++;b->provenance_sequence=prov;r=write_record(s,b);if(!r)*out=*b;pthread_mutex_unlock(&s->lock);return r;}
int fsb_query(const struct fsb_service*s,uint64_t id,struct fsb_sandbox*out){struct fsb_service*m=(struct fsb_service*)s;struct fsb_sandbox*b;if(!s||!out)return FSB_ERR_ARGUMENT;pthread_mutex_lock(&m->lock);b=find(m,id);if(!b){pthread_mutex_unlock(&m->lock);return FSB_ERR_NOT_FOUND;}*out=*b;pthread_mutex_unlock(&m->lock);return FSB_OK;}
int fsb_test_policy_matrix(struct fsb_service*s){struct fsb_policy p={.capability_mask=FSB_CAP_EXEC|FSB_CAP_COMMAND,.network_mask=0,.filesystem_mask=FSB_CAP_FILESYSTEM_READ,.cpu_quota_ns=1000000,.memory_bytes=4096,.require_verification=1};struct fsb_sandbox b;int r=fsb_create(s,FSB_COMMAND,1,0,1,"command",&p,&b);if(r)return r;if(fsb_admit(&b,FSB_CAP_COMMAND,0,FSB_CAP_FILESYSTEM_READ,1))return FSB_ERR_POLICY;return fsb_admit(&b,FSB_CAP_NETWORK,0,0,0)==FSB_ERR_POLICY?FSB_OK:FSB_ERR_POLICY;}
