#define _GNU_SOURCE
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "../../faisal-world-model/faisal_world_model_service.h"
#include "../../faisal-model-router/faisal_model_router.h"
static void fail(const char*m,int r){printf("M110_FAIL %s rc=%d\n",m,r);exit(1);}
#define WOK(x,m) do{int _rc=(x);if(_rc!=FWM_OK)fail(m,_rc);}while(0)
#define ROK(x,m) do{int _rc=(x);if(_rc!=FMR_OK)fail(m,_rc);}while(0)
#define REQ(x,e,m) do{int _rc=(x);if(_rc!=(e))fail(m,_rc);}while(0)
int main(void){char p[]="/tmp/faisal-m110-world-XXXXXX";struct fwm_service w;struct fwm_entity e;struct fwm_signal s,ss[4];uint32_t drift;size_t found;struct fmr_router r;struct fmr_model small,large,local;struct fmr_request q;struct fmr_route route;int fd=mkstemp(p);if(fd<0)fail("WORLD_TMP",FWM_ERR_IO);close(fd);unlink(p);WOK(fwm_open(&w,p),"WORLD_OPEN");printf("M110_WORLD_STATE_OPEN_OK\n");WOK(fwm_expect(&w,FWM_SERVICE,"inference-api","healthy",1,10,900000,&e),"EXPECT_SERVICE");WOK(fwm_observe(&w,FWM_SERVICE,"inference-api","degraded",2,11,700000,&e),"OBSERVE_SERVICE");WOK(fwm_reconcile(&w,3,12,&drift,ss,4,&found),"RECONCILE_DRIFT");if(drift!=1||found!=1||e.state!=FWM_DRIFTED||!e.actionable)fail("DRIFT_SIGNAL",FWM_ERR_CONFLICT);s=ss[0];WOK(fwm_query_signal(&w,s.signal_id,&s),"SIGNAL_QUERY");printf("M110_OBSERVED_EXPECTED_DRIFT_ACTIONABLE_OK drift=%u signals=%zu\n",drift,found);WOK(fwm_observe(&w,FWM_SERVICE,"inference-api","healthy",4,13,950000,&e),"OBSERVE_HEALTHY");WOK(fwm_reconcile(&w,5,14,&drift,ss,4,&found),"RECONCILE_RESOLVED");if(drift!=0||e.state!=FWM_CONSISTENT)fail("DRIFT_RESOLVE",FWM_ERR_CONFLICT);printf("M110_WORLD_RECONCILIATION_RESOLVED_OK\n");fwm_close(&w);WOK(fwm_open(&w,p),"WORLD_REPLAY");WOK(fwm_query(&w,e.entity_id,&e),"WORLD_REPLAY_QUERY");if(strcmp(e.observed,"healthy"))fail("WORLD_REPLAY_STATE",FWM_ERR_CORRUPT);printf("M110_WORLD_REPLAY_OK generation=%llu\n",(unsigned long long)e.generation);fwm_close(&w);fd=open(p,O_WRONLY|O_APPEND);if(fd<0||write(fd,"x",1)!=1)fail("WORLD_CORRUPT_APPEND",FWM_ERR_IO);close(fd);REQ(fwm_open(&w,p),FWM_ERR_CORRUPT,"WORLD_CORRUPTION");printf("M110_WORLD_REPLAY_FAIL_CLOSED_OK\n");unlink(p);
ROK(fmr_init(&r),"ROUTER_INIT");ROK(fmr_register(&r,"local-open","small-fast",FMR_LOCAL|FMR_OPEN,FMR_CODING|FMR_MULTIMODAL,980000,1000000,100,8192,1,1,950000,&small),"MODEL_SMALL");ROK(fmr_register(&r,"cloud-proprietary","large-reasoner",FMR_CLOUD|FMR_PROPRIETARY,FMR_REASONING|FMR_CODING|FMR_MULTIMODAL,990000,50000000,9000,128000,1,2,990000,&large),"MODEL_LARGE");ROK(fmr_register(&r,"local-vision","private-vision",FMR_LOCAL|FMR_OPEN,FMR_VISION|FMR_MULTIMODAL,900000,3000000,300,16384,3,1,880000,&local),"MODEL_LOCAL");for (int history = 0; history < 9; history++) ROK(fmr_record_result(&r, large.model_id, 1, 30000000, 980000), "MODEL_SUCCESS_HISTORY");
ROK(fmr_record_result(&r,large.model_id,0,90000000,980000),"MODEL_FAILURE_HISTORY");memset(&q,0,sizeof q);q.difficulty=900;q.required_modalities=FMR_REASONING;q.context_tokens=4000;q.allow_cloud=1;q.max_latency_ns=100000000;q.max_cost_micro=60000000;q.min_accuracy_ppm=900000;ROK(fmr_route(&r,&q,&route),"ROUTE_ESCALATE");if(route.model_id!=large.model_id||route.state!=FMR_ROUTE_ESCALATED)fail("ROUTE_LARGE",FMR_ERR_NO_ROUTE);printf("M110_SMALL_TO_LARGE_ESCALATION_OK model=%llu\n",(unsigned long long)route.model_id);memset(&q,0,sizeof q);q.difficulty=100;q.required_modalities=FMR_CODING;q.require_local=1;q.allow_cloud=0;q.context_tokens=100;q.max_cost_micro=2000000;q.min_accuracy_ppm=800000;ROK(fmr_route(&r,&q,&route),"ROUTE_DEESCALATE");if(route.model_id!=small.model_id||route.state!=FMR_ROUTE_DEESCALATED)fail("ROUTE_SMALL",FMR_ERR_NO_ROUTE);printf("M110_LARGE_TO_SMALL_COST_AWARE_OK model=%llu\n",(unsigned long long)route.model_id);memset(&q,0,sizeof q);q.required_modalities=FMR_SPEECH;q.allow_cloud=0;REQ(fmr_route(&r,&q,&route),FMR_ERR_NO_ROUTE,"ROUTE_DENY");printf("M110_PROVIDER_PRIVACY_LOCALITY_FILTER_OK\n");printf("M110_SELFTEST_EXIT=0\n");return 0;}
