#define _GNU_SOURCE
#include "faisal_world_model_service.h"
#include <fcntl.h>
#include <openssl/evp.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
struct fwm_hdr { uint32_t magic; uint16_t version,kind; uint32_t size; uint64_t sequence; };
enum { FWM_REC_ENTITY=1,FWM_REC_SIGNAL=2 };
static void dg(const char *s,uint8_t out[32]){EVP_MD_CTX*c=EVP_MD_CTX_new();unsigned n=0;if(!c||!EVP_DigestInit_ex(c,EVP_sha256(),0)||!EVP_DigestUpdate(c,s,strlen(s))||!EVP_DigestFinal_ex(c,out,&n)||n!=32)memset(out,0,32);EVP_MD_CTX_free(c);}
static struct fwm_entity* ent(struct fwm_service*s,uint64_t id){size_t i;for(i=0;i<s->entity_count;i++)if(s->entities[i].entity_id==id)return&s->entities[i];return 0;}
static int wr(struct fwm_service*s,uint16_t k,const void*p,uint32_t z){struct fwm_hdr h={FWM_MAGIC,FWM_VERSION,k,z,s->next_sequence++};if(write(s->fd,&h,sizeof h)!=sizeof h||write(s->fd,p,z)!=(ssize_t)z||fsync(s->fd)<0)return FWM_ERR_IO;return FWM_OK;}
int fwm_replay(struct fwm_service*s){struct fwm_hdr h;uint8_t p[sizeof(struct fwm_entity)>sizeof(struct fwm_signal)?sizeof(struct fwm_entity):sizeof(struct fwm_signal)];if(!s||lseek(s->fd,0,SEEK_SET)<0)return FWM_ERR_ARGUMENT;s->entity_count=s->signal_count=0;s->next_sequence=1;for(;;){ssize_t n=read(s->fd,&h,sizeof h);if(!n)break;if(n!=sizeof h||h.magic!=FWM_MAGIC||h.version!=FWM_VERSION||h.size>sizeof p||read(s->fd,p,h.size)!=(ssize_t)h.size)return FWM_ERR_CORRUPT;if(h.kind==FWM_REC_ENTITY&&h.size==sizeof(struct fwm_entity)){struct fwm_entity*r=(struct fwm_entity*)p,*o=ent(s,r->entity_id);if(o)*o=*r;else if(s->entity_count<FWM_MAX_ENTITIES)s->entities[s->entity_count++]=*r;else return FWM_ERR_FULL;}else if(h.kind==FWM_REC_SIGNAL&&h.size==sizeof(struct fwm_signal)){if(s->signal_count>=FWM_MAX_SIGNALS)return FWM_ERR_FULL;s->signals[s->signal_count++]=*(struct fwm_signal*)p;}else return FWM_ERR_CORRUPT;s->next_sequence=h.sequence+1;}return lseek(s->fd,0,SEEK_END)<0?FWM_ERR_IO:FWM_OK;}
int fwm_open(struct fwm_service*s,const char*path){int rc;if(!s||!path||strlen(path)>=sizeof s->path)return FWM_ERR_ARGUMENT;memset(s,0,sizeof*s);s->fd=open(path,O_RDWR|O_CREAT|O_APPEND,0600);if(s->fd<0)return FWM_ERR_IO;strncpy(s->path,path,sizeof(s->path)-1);pthread_mutex_init(&s->lock,0);s->lock_initialized=1;s->next_entity_id=s->next_signal_id=s->next_sequence=1;rc=fwm_replay(s);if(rc)fwm_close(s);return rc;}
void fwm_close(struct fwm_service*s){if(!s)return;if(s->lock_initialized)pthread_mutex_destroy(&s->lock);s->lock_initialized=0;if(s->fd>=0)close(s->fd);s->fd=-1;}
static int update(struct fwm_service*s,uint32_t type,const char*n,const char*v,uint64_t now,uint64_t prov,uint32_t conf,int expected,struct fwm_entity*out){struct fwm_entity*r;size_t i;if(!s||!n||!v||!out||!type||strlen(n)>=FWM_MAX_NAME||strlen(v)>=FWM_MAX_TEXT)return FWM_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);for(i=0;i<s->entity_count;i++)if(s->entities[i].type==type&&!strcmp(s->entities[i].name,n))break;if(i==s->entity_count){if(s->entity_count>=FWM_MAX_ENTITIES){pthread_mutex_unlock(&s->lock);return FWM_ERR_FULL;}r=&s->entities[s->entity_count++];memset(r,0,sizeof*r);r->entity_id=s->next_entity_id++;}else r=&s->entities[i];r->generation=++s->generation;r->type=type;r->provenance_sequence=prov;r->confidence_ppm=conf;snprintf(r->type_name,sizeof r->type_name,"type-%u",type);strncpy(r->name,n,sizeof r->name-1);if(expected){r->expected_at_ns=now;strncpy(r->expected,v,sizeof r->expected-1);dg(v,r->expected_digest);}else{r->observed_at_ns=now;strncpy(r->observed,v,sizeof r->observed-1);dg(v,r->observed_digest);}if(!strcmp(r->observed,r->expected)&&r->observed[0])r->state=FWM_CONSISTENT;else if(r->observed[0]&&r->expected[0])r->state=FWM_DRIFTED;else r->state=FWM_UNKNOWN;r->actionable=r->state==FWM_DRIFTED;int rc=wr(s,FWM_REC_ENTITY,r,sizeof*r);if(rc==FWM_OK)*out=*r;pthread_mutex_unlock(&s->lock);return rc;}
int fwm_observe(struct fwm_service*s,uint32_t t,const char*n,const char*v,uint64_t now,uint64_t p,uint32_t c,struct fwm_entity*out){return update(s,t,n,v,now,p,c,0,out);}
int fwm_expect(struct fwm_service*s,uint32_t t,const char*n,const char*v,uint64_t now,uint64_t p,uint32_t c,struct fwm_entity*out){return update(s,t,n,v,now,p,c,1,out);}
int fwm_reconcile(struct fwm_service*s,uint64_t now,uint64_t prov,uint32_t*drift,struct fwm_signal*out,size_t n,size_t*found){size_t i,c=0;uint32_t d=0;if(!s||!drift||!out||!found)return FWM_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);for(i=0;i<s->entity_count;i++){struct fwm_entity*r=&s->entities[i];if(r->expected[0]&&r->observed[0]&&strcmp(r->expected,r->observed)){r->state=FWM_DRIFTED;r->actionable=1;d++;if(c<n){struct fwm_signal sig={.signal_id=s->next_signal_id++,.entity_id=r->entity_id,.generation=++s->generation,.created_at_ns=now,.provenance_sequence=prov,.type=1,.severity=r->confidence_ppm<500000?3:2,.actionable=1};snprintf(sig.reason,sizeof sig.reason,"observed differs from expected for %s",r->name);s->signals[s->signal_count<FWM_MAX_SIGNALS?s->signal_count++:FWM_MAX_SIGNALS-1]=sig;wr(s,FWM_REC_SIGNAL,&sig,sizeof sig);out[c++]=sig;wr(s,FWM_REC_ENTITY,r,sizeof*r);}}else if(r->expected[0]&&r->observed[0]){r->state=FWM_CONSISTENT;r->actionable=0;wr(s,FWM_REC_ENTITY,r,sizeof*r);}}*drift=d;*found=c;pthread_mutex_unlock(&s->lock);return FWM_OK;}
int fwm_query(const struct fwm_service*s,uint64_t id,struct fwm_entity*out){struct fwm_service*m=(struct fwm_service*)s;struct fwm_entity*r;if(!s||!out)return FWM_ERR_ARGUMENT;pthread_mutex_lock(&m->lock);r=ent(m,id);if(!r){pthread_mutex_unlock(&m->lock);return FWM_ERR_NOT_FOUND;}*out=*r;pthread_mutex_unlock(&m->lock);return FWM_OK;}
int fwm_query_signal(const struct fwm_service*s,uint64_t id,struct fwm_signal*out){struct fwm_service*m=(struct fwm_service*)s;size_t i;if(!s||!out)return FWM_ERR_ARGUMENT;pthread_mutex_lock(&m->lock);for(i=0;i<m->signal_count;i++)if(m->signals[i].signal_id==id){*out=m->signals[i];pthread_mutex_unlock(&m->lock);return FWM_OK;}pthread_mutex_unlock(&m->lock);return FWM_ERR_NOT_FOUND;}
