#!/usr/bin/env python3
from __future__ import annotations
import json,os,subprocess,tempfile,time
from pathlib import Path
import verify_cve_operations as v
def main():
 root=Path(tempfile.mkdtemp(prefix='faisal-cve-ops-test-')); key=root/'key.pem'; pub=root/'pub.pem'; subprocess.run(['openssl','genpkey','-algorithm','RSA','-pkeyopt','rsa_keygen_bits:2048','-out',str(key)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL); os.chmod(key,0o600); subprocess.run(['openssl','pkey','-in',str(key),'-pubout','-out',str(pub)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
 now=int(time.time()); sources=[{'id':'linux-upstream','url':'https://kernel.org/security','snapshot_sha256':'a'*64,'retrieved_epoch':now},{'id':'cisa-kev','url':'https://www.cisa.gov/known-exploited-vulnerabilities-catalog','snapshot_sha256':'b'*64,'retrieved_epoch':now},{'id':'nvd','url':'https://nvd.nist.gov/','snapshot_sha256':'c'*64,'retrieved_epoch':now}]
 d={'schema':v.SCHEMA,'status':'operator_owned_cve_workflow_qualified','source_revision':'candidate-1','reviewed_epoch':now,'model_output_is_authority':False,'operator_owner':{'live':True,'operator_confirmed':True,'workflow_id':'secops-prod-001','team':'FAISAL Security Response','account_id':'secops-operator-7','contact':'security@example.invalid','escalation_contact':'oncall@example.invalid','key_fingerprint':'d'*64,'ack_receipt':'ack-001'},'upstream_sync':{'live':True,'job_id':'sync-001','completed_epoch':now,'source_count':3,'all_sources_current':True,'auth_receipt':'sync-receipt-001','sources':sources},'lifecycle':{'intake_receipt':'intake-001','triage_receipt':'triage-001','remediation_receipt':'remediate-001','disclosure_receipt':'disclose-001','post_release_review_receipt':'review-001','sla_policy_version':'cve-sla-v1','overdue_open_advisories':0,'unresolved_blocking_advisories':0,'operator_escalation_tested':True},'ledger':{'path':'/external/ledger.json','sha256':'e'*64,'validator_status':'pass','operator_signature_verified':True},'external_security_feedback':{'live':True,'reviewer_identity':'external-reviewer-001','feedback_receipt':'feedback-001','report_sha256':'f'*64,'candidate_source_revision':'candidate-1','remediation_retest_status':'pass','unresolved_critical_high':0,'feedback_integrated':True},'disclosure':{'policy_version':'cvd-v1','coordinated_process_tested':True,'embargo_and_publication_tested':True,'cna_status':'not_applicable_with_rationale'},'limitations':[],'production_status':'operator_owned_workflow_only_other_release_gates_pending'}
 p=root/'report.json'; p.write_text(json.dumps(d,sort_keys=True,separators=(',',':'))+'\n'); subprocess.run(['openssl','dgst','-sha256','-sign',str(key),'-out',str(p)+'.sig',str(p)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL); v.verify(p,pub,'candidate-1',now,3600)
 for name,mutate in [('fixture',lambda x:x['operator_owner'].update(account_id='sandbox-fixture')),('no_sync',lambda x:x['upstream_sync'].update(all_sources_current=False)),('no_feedback',lambda x:x['external_security_feedback'].update(feedback_integrated=False)),('overdue',lambda x:x['lifecycle'].update(overdue_open_advisories=1)),('model',lambda x:x.update(model_output_is_authority=True))]:
  bad=json.loads(p.read_text()); mutate(bad); q=root/(name+'.json'); q.write_text(json.dumps(bad,sort_keys=True,separators=(',',':'))+'\n'); subprocess.run(['openssl','dgst','-sha256','-sign',str(key),'-out',str(q)+'.sig',str(q)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
  try: v.verify(q,pub,'candidate-1',now,3600)
  except ValueError: pass
  else: raise AssertionError(name+' accepted')
 print('FAISAL_CVE_OPERATIONS_VALIDATOR_TEST_OK positive_owner_sync_feedback_and_denials')
if __name__=='__main__': main()
