# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import faisal_replication_pb2 as faisal__replication__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in faisal_replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JournalReplicationStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/faisal.replication.v1.JournalReplication/RequestVote',
                request_serializer=faisal__replication__pb2.VoteRequest.SerializeToString,
                response_deserializer=faisal__replication__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/faisal.replication.v1.JournalReplication/AppendEntries',
                request_serializer=faisal__replication__pb2.AppendRequest.SerializeToString,
                response_deserializer=faisal__replication__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.AppendJournal = channel.unary_unary(
                '/faisal.replication.v1.JournalReplication/AppendJournal',
                request_serializer=faisal__replication__pb2.AppendRequest.SerializeToString,
                response_deserializer=faisal__replication__pb2.AppendResponse.FromString,
                _registered_method=True)
        self.InstallSnapshot = channel.unary_unary(
                '/faisal.replication.v1.JournalReplication/InstallSnapshot',
                request_serializer=faisal__replication__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=faisal__replication__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.ReadCommit = channel.unary_unary(
                '/faisal.replication.v1.JournalReplication/ReadCommit',
                request_serializer=faisal__replication__pb2.ReadCommitRequest.SerializeToString,
                response_deserializer=faisal__replication__pb2.ReadCommitResponse.FromString,
                _registered_method=True)


class JournalReplicationServicer:
    """Missing associated documentation comment in .proto file."""

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendJournal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JournalReplicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=faisal__replication__pb2.VoteRequest.FromString,
                    response_serializer=faisal__replication__pb2.VoteResponse.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=faisal__replication__pb2.AppendRequest.FromString,
                    response_serializer=faisal__replication__pb2.AppendResponse.SerializeToString,
            ),
            'AppendJournal': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendJournal,
                    request_deserializer=faisal__replication__pb2.AppendRequest.FromString,
                    response_serializer=faisal__replication__pb2.AppendResponse.SerializeToString,
            ),
            'InstallSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallSnapshot,
                    request_deserializer=faisal__replication__pb2.SnapshotRequest.FromString,
                    response_serializer=faisal__replication__pb2.SnapshotResponse.SerializeToString,
            ),
            'ReadCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadCommit,
                    request_deserializer=faisal__replication__pb2.ReadCommitRequest.FromString,
                    response_serializer=faisal__replication__pb2.ReadCommitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'faisal.replication.v1.JournalReplication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('faisal.replication.v1.JournalReplication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JournalReplication:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faisal.replication.v1.JournalReplication/RequestVote',
            faisal__replication__pb2.VoteRequest.SerializeToString,
            faisal__replication__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faisal.replication.v1.JournalReplication/AppendEntries',
            faisal__replication__pb2.AppendRequest.SerializeToString,
            faisal__replication__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendJournal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faisal.replication.v1.JournalReplication/AppendJournal',
            faisal__replication__pb2.AppendRequest.SerializeToString,
            faisal__replication__pb2.AppendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faisal.replication.v1.JournalReplication/InstallSnapshot',
            faisal__replication__pb2.SnapshotRequest.SerializeToString,
            faisal__replication__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faisal.replication.v1.JournalReplication/ReadCommit',
            faisal__replication__pb2.ReadCommitRequest.SerializeToString,
            faisal__replication__pb2.ReadCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
