#define _GNU_SOURCE
#include "faisal_repo_adapter.h"
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <openssl/evp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
struct fra_hdr { uint32_t magic; uint16_t version,kind; uint32_t size; uint64_t sequence; };
enum { FRA_REC_FILE=1,FRA_REC_WORKSPACE=2 };
static struct fra_file *find(struct fra_service*s,const char*p){size_t i;for(i=0;i<s->file_count;i++)if(!strcmp(s->files[i].path,p))return&s->files[i];return 0;}
static int append(struct fra_service*s,uint16_t k,const void*p,uint32_t n){struct fra_hdr h={FRA_MAGIC,FRA_VERSION,k,n,s->next_sequence++};if(write(s->fd,&h,sizeof h)!=(ssize_t)sizeof h||write(s->fd,p,n)!=(ssize_t)n||fsync(s->fd)<0)return FRA_ERR_IO;return FRA_OK;}
int fra_reject_path(const char*p){if(!p||!p[0]||p[0]=='/'||strstr(p,"..")||strchr(p,'\\'))return FRA_ERR_POLICY;return FRA_OK;}
static int digest_file(const char*p,uint8_t d[FRA_MAX_DIGEST],uint64_t*size){int fd;unsigned char buf[8192];ssize_t n;unsigned int len=0;EVP_MD_CTX*c;if(!p||!d||!size)return FRA_ERR_ARGUMENT;fd=open(p,O_RDONLY|O_NOFOLLOW);if(fd<0)return FRA_ERR_IO;c=EVP_MD_CTX_new();if(!c||EVP_DigestInit_ex(c,EVP_sha256(),0)!=1){if(c)EVP_MD_CTX_free(c);close(fd);return FRA_ERR_IO;}*size=0;while((n=read(fd,buf,sizeof buf))>0){if(EVP_DigestUpdate(c,buf,(size_t)n)!=1){EVP_MD_CTX_free(c);close(fd);return FRA_ERR_IO;}*size+=(uint64_t)n;if(*size>FRA_MAX_BYTES){EVP_MD_CTX_free(c);close(fd);return FRA_ERR_POLICY;}}close(fd);if(n<0||EVP_DigestFinal_ex(c,d,&len)!=1||len!=FRA_MAX_DIGEST){EVP_MD_CTX_free(c);return FRA_ERR_IO;}EVP_MD_CTX_free(c);return FRA_OK;}
static int make_parent(const char*p){char b[4096],*q;if(strlen(p)>=sizeof b)return FRA_ERR_POLICY;strncpy(b,p,sizeof b-1);b[sizeof b-1]=0;q=strrchr(b,'/');if(!q)return FRA_OK;*q=0;if(!b[0])return FRA_OK;char cur[4096]="";for(char*tok=strtok(b,"/");tok;tok=strtok(0,"/")){if(cur[0])strncat(cur,"/",sizeof cur-strlen(cur)-1);strncat(cur,tok,sizeof cur-strlen(cur)-1);if(mkdir(cur,0700)<0&&errno!=EEXIST)return FRA_ERR_IO;}return FRA_OK;}
static int copy_file(const char*src,const char*dst){int in=open(src,O_RDONLY|O_NOFOLLOW),out;if(in<0)return FRA_ERR_IO;if(make_parent(dst)){close(in);return FRA_ERR_IO;}out=open(dst,O_WRONLY|O_CREAT|O_TRUNC|O_NOFOLLOW,0600);if(out<0){close(in);return FRA_ERR_IO;}char b[8192];ssize_t n;int r=FRA_OK;while((n=read(in,b,sizeof b))>0)if(write(out,b,(size_t)n)!=n){r=FRA_ERR_IO;break;}if(n<0)r=FRA_ERR_IO;fsync(out);close(in);close(out);return r;}
static int walk(struct fra_service*s,const char*base,const char*rel){DIR*d;struct dirent*e;if(s->file_count>=FRA_MAX_FILES)return FRA_ERR_FULL;d=opendir(base);if(!d)return FRA_ERR_IO;while((e=readdir(d))){char full[4096],next[FRA_MAX_PATH];struct stat st;int n;if(!strcmp(e->d_name,".")||!strcmp(e->d_name,"..")||!strcmp(e->d_name,".faisal-backups"))continue;n=snprintf(full,sizeof full,"%s/%s",base,e->d_name);if(n<0||(size_t)n>=sizeof full){closedir(d);return FRA_ERR_POLICY;}n=rel[0]?snprintf(next,sizeof next,"%s/%s",rel,e->d_name):snprintf(next,sizeof next,"%s",e->d_name);if(n<0||(size_t)n>=sizeof next){closedir(d);return FRA_ERR_POLICY;}if(lstat(full,&st)<0){closedir(d);return FRA_ERR_IO;}if(S_ISDIR(st.st_mode)){int r=walk(s,full,next);if(r){closedir(d);return r;}}else if(S_ISREG(st.st_mode)){struct fra_file*f=&s->files[s->file_count++];memset(f,0,sizeof*f);if(snprintf(f->path,sizeof f->path,"%s",next)>=(int)sizeof f->path){closedir(d);return FRA_ERR_POLICY;}f->mode=st.st_mode;f->regular=1;int r=digest_file(full,f->digest,&f->size);if(r||append(s,FRA_REC_FILE,f,sizeof*f)){closedir(d);return r?r:FRA_ERR_IO;}}}closedir(d);return FRA_OK;}
static void tree_digest(struct fra_service*s){EVP_MD_CTX*c=EVP_MD_CTX_new();size_t i;unsigned int n;if(!c||EVP_DigestInit_ex(c,EVP_sha256(),0)!=1){if(c)EVP_MD_CTX_free(c);memset(s->workspace.tree_digest,0,sizeof s->workspace.tree_digest);return;}for(i=0;i<s->file_count;i++){EVP_DigestUpdate(c,s->files[i].path,strlen(s->files[i].path));EVP_DigestUpdate(c,s->files[i].digest,sizeof s->files[i].digest);}EVP_DigestFinal_ex(c,s->workspace.tree_digest,&n);EVP_MD_CTX_free(c);}
int fra_open(struct fra_service*s,const char*root,const char*journal){if(!s||!root||!journal||strlen(root)>=sizeof s->root||strlen(journal)>=sizeof s->journal)return FRA_ERR_ARGUMENT;memset(s,0,sizeof*s);if(!realpath(root,s->root))return FRA_ERR_IO;strncpy(s->journal,journal,sizeof s->journal-1);s->fd=open(journal,O_RDWR|O_CREAT|O_APPEND,0600);if(s->fd<0)return FRA_ERR_IO;pthread_mutex_init(&s->lock,0);s->lock_initialized=1;s->next_sequence=1;int r=fra_replay(s);if(r)fra_close(s);return r;}
void fra_close(struct fra_service*s){if(!s)return;if(s->lock_initialized)pthread_mutex_destroy(&s->lock);s->lock_initialized=0;if(s->fd>=0)close(s->fd);s->fd=-1;}
int fra_replay(struct fra_service*s){struct fra_hdr h;unsigned char b[sizeof(struct fra_file)>sizeof(struct fra_workspace)?sizeof(struct fra_file):sizeof(struct fra_workspace)];if(!s||lseek(s->fd,0,SEEK_SET)<0)return FRA_ERR_ARGUMENT;s->file_count=0;memset(&s->workspace,0,sizeof s->workspace);for(;;){ssize_t n=read(s->fd,&h,sizeof h);if(!n)break;if(n!=(ssize_t)sizeof h||h.magic!=FRA_MAGIC||h.version!=FRA_VERSION||h.size>sizeof b)return FRA_ERR_CORRUPT;if(read(s->fd,b,h.size)!=(ssize_t)h.size)return FRA_ERR_CORRUPT;if(h.kind==FRA_REC_FILE){struct fra_file*f=(struct fra_file*)b;struct fra_file*old=find(s,f->path);if(old)*old=*f;else if(s->file_count<FRA_MAX_FILES)s->files[s->file_count++]=*f;else return FRA_ERR_CORRUPT;}else if(h.kind==FRA_REC_WORKSPACE){if(h.size!=sizeof s->workspace)return FRA_ERR_CORRUPT;s->workspace=*(struct fra_workspace*)b;}else return FRA_ERR_CORRUPT;s->next_sequence=h.sequence+1;}return lseek(s->fd,0,SEEK_END)<0?FRA_ERR_IO:FRA_OK;}
int fra_analyze(struct fra_service*s,uint64_t prov,struct fra_workspace*out){int r;if(!s||!out)return FRA_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);s->file_count=0;r=walk(s,s->root,"");if(!r){s->workspace.generation++;s->workspace.provenance_sequence=prov;s->workspace.file_count=(uint32_t)s->file_count;s->workspace.changed_count=0;tree_digest(s);r=append(s,FRA_REC_WORKSPACE,&s->workspace,sizeof s->workspace);if(!r)*out=s->workspace;}pthread_mutex_unlock(&s->lock);return r;}
int fra_query_file(const struct fra_service*s,const char*p,struct fra_file*out){struct fra_service*m=(struct fra_service*)s;struct fra_file*f;if(!s||!out||fra_reject_path(p))return FRA_ERR_ARGUMENT;pthread_mutex_lock(&m->lock);f=find(m,p);if(!f){pthread_mutex_unlock(&m->lock);return FRA_ERR_NOT_FOUND;}*out=*f;pthread_mutex_unlock(&m->lock);return FRA_OK;}
int fra_stage_write(struct fra_service*s,const char*p,const void*data,size_t n,uint64_t prov,struct fra_file*out){char full[4096],bdir[4096],backup[4096];struct fra_file*f;int r,fd;if(!s||!data||!out||n>FRA_MAX_BYTES||fra_reject_path(p))return FRA_ERR_POLICY;pthread_mutex_lock(&s->lock);if(snprintf(full,sizeof full,"%s/%s",s->root,p)>= (int)sizeof full||snprintf(bdir,sizeof bdir,"%s/.faisal-backups",s->root)>= (int)sizeof bdir||snprintf(backup,sizeof backup,"%s/.faisal-backups/%s",s->root,p)>= (int)sizeof backup){pthread_mutex_unlock(&s->lock);return FRA_ERR_POLICY;}if(make_parent(backup)||(mkdir(bdir,0700)<0&&errno!=EEXIST)){pthread_mutex_unlock(&s->lock);return FRA_ERR_IO;}if(access(full,F_OK)==0&&copy_file(full,backup)){pthread_mutex_unlock(&s->lock);return FRA_ERR_IO;}if(make_parent(full)){pthread_mutex_unlock(&s->lock);return FRA_ERR_IO;}fd=open(full,O_WRONLY|O_CREAT|O_TRUNC|O_NOFOLLOW,0600);if(fd<0){pthread_mutex_unlock(&s->lock);return FRA_ERR_IO;}if(write(fd,data,n)!=(ssize_t)n){close(fd);pthread_mutex_unlock(&s->lock);return FRA_ERR_IO;}fsync(fd);close(fd);f=find(s,p);if(!f&&s->file_count<FRA_MAX_FILES){f=&s->files[s->file_count++];memset(f,0,sizeof*f);if(snprintf(f->path,sizeof f->path,"%s",p)>=(int)sizeof f->path){pthread_mutex_unlock(&s->lock);return FRA_ERR_POLICY;}f->regular=1;}if(!f){pthread_mutex_unlock(&s->lock);return FRA_ERR_FULL;}r=digest_file(full,f->digest,&f->size);if(snprintf(f->backup_path,sizeof f->backup_path,"%s",backup)>=(int)sizeof f->backup_path){pthread_mutex_unlock(&s->lock);return FRA_ERR_POLICY;}f->staged=1;f->version++;s->workspace.changed_count++;s->workspace.provenance_sequence=prov;tree_digest(s);if(!r)r=append(s,FRA_REC_FILE,f,sizeof*f);if(!r)*out=*f;pthread_mutex_unlock(&s->lock);return r;}
int fra_rollback(struct fra_service*s,uint64_t prov,struct fra_workspace*out){size_t i;int r=FRA_OK;if(!s||!out)return FRA_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);for(i=0;i<s->file_count;i++)if(s->files[i].staged&&s->files[i].backup_path[0]){char full[4096];if(snprintf(full,sizeof full,"%s/%s",s->root,s->files[i].path)>= (int)sizeof full){r=FRA_ERR_POLICY;break;}r=copy_file(s->files[i].backup_path,full);if(r)break;s->files[i].staged=0;s->files[i].backup_path[0]=0;append(s,FRA_REC_FILE,&s->files[i],sizeof s->files[i]);}s->workspace.generation++;s->workspace.provenance_sequence=prov;s->workspace.changed_count=0;tree_digest(s);if(!r)r=append(s,FRA_REC_WORKSPACE,&s->workspace,sizeof s->workspace);if(!r)*out=s->workspace;pthread_mutex_unlock(&s->lock);return r;}
int fra_test_corruption(struct fra_service*s){if(!s)return FRA_ERR_ARGUMENT;return write(s->fd,"x",1)==1?FRA_OK:FRA_ERR_IO;}
