#define _GNU_SOURCE
#include "faisal_engineering_service.h"
#include <fcntl.h>
#include <string.h>
#include <unistd.h>
#include <stdio.h>
struct fen_hdr { uint32_t magic; uint16_t version,kind; uint32_t size; uint64_t sequence; };
enum { FEN_REC_REPO=1,FEN_REC_CHANGE=2 };
static struct fen_repo*repo(struct fen_service*s,uint64_t id){size_t i;for(i=0;i<s->repo_count;i++)if(s->repos[i].repo_id==id)return&s->repos[i];return 0;}
static struct fen_change*change(struct fen_service*s,uint64_t id){size_t i;for(i=0;i<s->change_count;i++)if(s->changes[i].change_id==id)return&s->changes[i];return 0;}
static int append(struct fen_service*s,uint16_t k,const void*p,uint32_t n){struct fen_hdr h={FEN_MAGIC,FEN_VERSION,k,n,s->next_sequence++};if(write(s->fd,&h,sizeof h)!=(ssize_t)sizeof h||write(s->fd,p,n)!=(ssize_t)n||fsync(s->fd)<0)return FEN_ERR_IO;return FEN_OK;}
int fen_replay(struct fen_service*s){struct fen_hdr h;uint8_t buf[sizeof(struct fen_change)>sizeof(struct fen_repo)?sizeof(struct fen_change):sizeof(struct fen_repo)];if(!s||lseek(s->fd,0,SEEK_SET)<0)return FEN_ERR_ARGUMENT;s->repo_count=s->change_count=0;s->next_sequence=1;for(;;){ssize_t n=read(s->fd,&h,sizeof h);if(!n)break;if(n!=(ssize_t)sizeof h||h.magic!=FEN_MAGIC||h.version!=FEN_VERSION||h.size>sizeof buf)return FEN_ERR_CORRUPT;if(read(s->fd,buf,h.size)!=(ssize_t)h.size)return FEN_ERR_CORRUPT;if(h.kind==FEN_REC_REPO){struct fen_repo*x=(struct fen_repo*)buf;struct fen_repo*old=repo(s,x->repo_id);if(old)*old=*x;else if(s->repo_count<FEN_MAX_REPOS)s->repos[s->repo_count++]=*x;else return FEN_ERR_CORRUPT;if(x->repo_id>=s->next_repo)s->next_repo=x->repo_id+1;}else if(h.kind==FEN_REC_CHANGE){struct fen_change*x=(struct fen_change*)buf;struct fen_change*old=change(s,x->change_id);if(old)*old=*x;else if(s->change_count<FEN_MAX_CHANGES)s->changes[s->change_count++]=*x;else return FEN_ERR_CORRUPT;if(x->change_id>=s->next_change)s->next_change=x->change_id+1;}else return FEN_ERR_CORRUPT;s->next_sequence=h.sequence+1;}return lseek(s->fd,0,SEEK_END)<0?FEN_ERR_IO:FEN_OK;}
int fen_open(struct fen_service*s,const char*p){if(!s||!p||strlen(p)>=sizeof s->path)return FEN_ERR_ARGUMENT;memset(s,0,sizeof*s);s->fd=open(p,O_RDWR|O_CREAT|O_APPEND,0600);if(s->fd<0)return FEN_ERR_IO;strncpy(s->path,p,sizeof s->path-1);pthread_mutex_init(&s->lock,0);s->lock_initialized=1;s->next_repo=s->next_change=s->next_sequence=1;int r=fen_replay(s);if(r)fen_close(s);return r;}
void fen_close(struct fen_service*s){if(!s)return;if(s->lock_initialized)pthread_mutex_destroy(&s->lock);s->lock_initialized=0;if(s->fd>=0)close(s->fd);s->fd=-1;}
int fen_register_repo(struct fen_service*s,uint32_t tenant,const char*n,const uint8_t d[FEN_DIGEST_SIZE],struct fen_repo*out){struct fen_repo*x;int r;if(!s||!n||!d||!out||!n[0]||strlen(n)>=FEN_MAX_NAME)return FEN_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);if(s->repo_count>=FEN_MAX_REPOS){pthread_mutex_unlock(&s->lock);return FEN_ERR_FULL;}x=&s->repos[s->repo_count++];memset(x,0,sizeof*x);x->repo_id=s->next_repo++;x->generation=1;x->tenant_id=tenant;x->clean=1;memcpy(x->ref_digest,d,FEN_DIGEST_SIZE);strncpy(x->name,n,sizeof x->name-1);r=append(s,FEN_REC_REPO,x,sizeof*x);if(!r)*out=*x;pthread_mutex_unlock(&s->lock);return r;}
int fen_propose_change(struct fen_service*s,uint64_t rid,uint64_t agent,const char*t,const uint8_t src[FEN_DIGEST_SIZE],const uint8_t patch[FEN_DIGEST_SIZE],uint32_t model,struct fen_change*out){struct fen_change*x;int r;if(!s||!t||!src||!patch||!out||!t[0]||!repo(s,rid))return FEN_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);if(s->change_count>=FEN_MAX_CHANGES){pthread_mutex_unlock(&s->lock);return FEN_ERR_FULL;}x=&s->changes[s->change_count++];memset(x,0,sizeof*x);x->change_id=s->next_change++;x->repo_id=rid;x->agent_id=agent;x->generation=1;x->state=FEN_PROPOSED;x->model_proposed=model;x->provenance_sequence=s->next_sequence;memcpy(x->source_digest,src,FEN_DIGEST_SIZE);memcpy(x->patch_digest,patch,FEN_DIGEST_SIZE);strncpy(x->title,t,sizeof x->title-1);r=append(s,FEN_REC_CHANGE,x,sizeof*x);if(!r)*out=*x;pthread_mutex_unlock(&s->lock);return r;}
int fen_record_check(struct fen_service*s,uint64_t id,uint32_t kind,uint32_t status,const uint8_t d[FEN_DIGEST_SIZE],const char*reason,struct fen_change*out){struct fen_change*x;int r;if(!s||!d||!out||kind<FEN_REPOSITORY||kind>FEN_REGRESSION)return FEN_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);x=change(s,id);if(!x){pthread_mutex_unlock(&s->lock);return FEN_ERR_NOT_FOUND;}if(x->state==FEN_DEPLOYED||x->state==FEN_ROLLED_BACK){pthread_mutex_unlock(&s->lock);return FEN_ERR_STATE;}if(x->check_count>=FEN_MAX_CHECKS){pthread_mutex_unlock(&s->lock);return FEN_ERR_FULL;}struct fen_check*c=&x->checks[x->check_count++];memset(c,0,sizeof*c);c->kind=kind;c->status=status;c->evidence_sequence=s->next_sequence;memcpy(c->evidence_digest,d,FEN_DIGEST_SIZE);if(reason)strncpy(c->reason,reason,sizeof c->reason-1);x->state=FEN_TESTING;x->generation++;r=append(s,FEN_REC_CHANGE,x,sizeof*x);if(!r)*out=*x;pthread_mutex_unlock(&s->lock);return r;}
int fen_verify_change(struct fen_service*s,uint64_t id,uint64_t prov,struct fen_change*out){struct fen_change*x;uint32_t i;int r;if(!s||!out)return FEN_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);x=change(s,id);if(!x){pthread_mutex_unlock(&s->lock);return FEN_ERR_NOT_FOUND;}if(x->model_proposed&&!prov){pthread_mutex_unlock(&s->lock);return FEN_ERR_AUTHORITY;}if(x->check_count<8){pthread_mutex_unlock(&s->lock);return FEN_ERR_POLICY;}for(i=0;i<x->check_count;i++)if(x->checks[i].status!=0){pthread_mutex_unlock(&s->lock);return FEN_ERR_POLICY;}x->verified=1;x->provenance_sequence=prov;x->state=FEN_CANARY;x->generation++;r=append(s,FEN_REC_CHANGE,x,sizeof*x);if(!r)*out=*x;pthread_mutex_unlock(&s->lock);return r;}
int fen_canary(struct fen_service*s,uint64_t id,uint32_t ok,struct fen_change*out){struct fen_change*x;int r;if(!s||!out)return FEN_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);x=change(s,id);if(!x){pthread_mutex_unlock(&s->lock);return FEN_ERR_NOT_FOUND;}if(x->state!=FEN_CANARY||!x->verified){pthread_mutex_unlock(&s->lock);return FEN_ERR_STATE;}if(!ok){x->state=FEN_FAILED;pthread_mutex_unlock(&s->lock);return FEN_ERR_POLICY;}x->canary_passed=1;x->generation++;r=append(s,FEN_REC_CHANGE,x,sizeof*x);if(!r)*out=*x;pthread_mutex_unlock(&s->lock);return r;}
int fen_deploy(struct fen_service*s,uint64_t id,uint64_t approval,struct fen_change*out){struct fen_change*x;int r;if(!s||!out)return FEN_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);x=change(s,id);if(!x){pthread_mutex_unlock(&s->lock);return FEN_ERR_NOT_FOUND;}if(x->state!=FEN_CANARY||!x->verified||!x->canary_passed||!approval){pthread_mutex_unlock(&s->lock);return FEN_ERR_AUTHORITY;}x->state=FEN_DEPLOYED;x->generation++;r=append(s,FEN_REC_CHANGE,x,sizeof*x);if(!r)*out=*x;pthread_mutex_unlock(&s->lock);return r;}
int fen_rollback(struct fen_service*s,uint64_t id,uint32_t reason,struct fen_change*out){struct fen_change*x;int r;if(!s||!out)return FEN_ERR_ARGUMENT;pthread_mutex_lock(&s->lock);x=change(s,id);if(!x){pthread_mutex_unlock(&s->lock);return FEN_ERR_NOT_FOUND;}if(x->state!=FEN_DEPLOYED&&x->state!=FEN_CANARY){pthread_mutex_unlock(&s->lock);return FEN_ERR_STATE;}x->state=FEN_ROLLED_BACK;x->rollback_reason=reason;x->generation++;r=append(s,FEN_REC_CHANGE,x,sizeof*x);if(!r)*out=*x;pthread_mutex_unlock(&s->lock);return r;}
int fen_query(const struct fen_service*s,uint64_t id,struct fen_change*out){struct fen_service*m=(struct fen_service*)s;struct fen_change*x;if(!s||!out)return FEN_ERR_ARGUMENT;pthread_mutex_lock(&m->lock);x=change(m,id);if(!x){pthread_mutex_unlock(&m->lock);return FEN_ERR_NOT_FOUND;}*out=*x;pthread_mutex_unlock(&m->lock);return FEN_OK;}
int fen_test_model_proposal_denial(struct fen_service*s,uint64_t id){struct fen_change x;return fen_verify_change(s,id,0,&x)==FEN_ERR_AUTHORITY?FEN_OK:FEN_ERR_AUTHORITY;}
